### ISSUE TITLE
How to close a navigated child view from the main view in mvvmcross?

### ISSUE THREAD

**Issue by btylmz** [tuke307/Samples#40]
I'am pretty new in MVVMCross and I am using MVVMCross 8.0.2 for a **WPF** application. Basically what I'am trying to do is to have main view that have mode selections for the application. When i change the mode selection (with buttons) views shown on the main view should change. I used **Mvx.Wpf.ItemsPresenter** library for this purpose. I used the sample project provided in this repository.

In the main view inside a border I created a MvxContainer region. Two different views share the same region

    <Border Grid.Column="3" Grid.ColumnSpan="3" Grid.Row="1" Grid.RowSpan="5" BorderBrush="Blue" BorderThickness="5" >
            <ItemsControl region:MvxContainer.Id="NestedViewRegion"> </ItemsControl>
    </Border>

Red region is the main view, blue region is the child views i am navigating. Navigation works when i click the buttons. **Problem is that when i navigate with the buttons, both child views are added to the region.** What i want to do is to close one of them by using the same buttons which belongs to the main view.

For ex.: when i click navigate 1 button, first child view should appear, after i click the navigate 2 button first child view should close and second child view should appear.

I tried to use MvxPresentationHint to achieve that but i think it can just close the child view within the child viewmodel. Code below shows the navigation commands attached to buttons, this code is in the main viewmodel.

        public async Task FirstNavigateCommand()
        {
            //await _navigationService.ChangePresentation(new MvxClosePresentationHint());
            await _navigationService.Navigate<NestedViewModel>();
        }

        public async Task SecondNavigateCommand()
        {
            //
            await _navigationService.Navigate<NestedNestedViewModel>();
        }

I also tried to use Messenger plugin but couldn't manage to work with navigationservice.

Is there any way of achieving what i am trying to do?

**Comment by tuke307** [comment]
Hey, i can't look into your issue more deeply right now because I'am only having my phone with me. But I'am trying to help you roughly.

try it with an interaction trigger for also closing the view the holder.

Add the namespace in your xaml view

```xaml
xmlns:i="http://schemas.microsoft.com/xaml/behaviors"
```

And when you're clicking one of your buttons add this trigger to close the holder

```xaml
<i:Interaction.Triggers>
                              <i:EventTrigger EventName="Click">
                                    <i:InvokeCommandAction Command="{x:Static region:MvxWpfPresenter.CloseHolderCommand}"
                                                           CommandParameter="NestedViewRegion">
                                    </i:InvokeCommandAction>
                                <i:EventTrigger>
                            </i:Interaction.Triggers>
```

**Comment by btylmz** [comment]
Thank you so much for your quick response. I should've read the GUI commands in the repository of ItemPresenter. Now it is working as i wanted, CloseHolderCommand does not initially shows the views and program crashes. CloseViewCommand solved my problem though. 

Thank you very much.
